version: '3.1'

services:


###> doctrine/doctrine-bundle ###
  database:
    image: postgres:15-alpine
    ports:
        - "5432:5432"
    environment:
      POSTGRES_DB: test
      # You should definitely change the password in production
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - winlassie_db:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

###> doctrine/doctrine-bundle ###
volumes:
  winlassie_db:
###< doctrine/doctrine-bundle ###
