version: '3.1'

services:

    db:
        image: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER_PASSWORD: test
            MARIADB_PASSWORD: test
            MARIADB_DATABASE: test
        ports:
            - 3308:3306
        volumes:
            - winlassie_test_db:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    winlassie_test_db:
        name: winlassie_test_db
